[wal]
version = 1

[memtable]
max_entries = 5

[directory]
wal = "data/wals"
ss_table = "data/ss_tables"
log = "log/config/log4rs.yaml"

[cache]
index_size = 5
bloom_filter_size = 50

[ss_table]
manifest_location = "./manifest.json"
l0_file_count_limit = 3
l1_file_size_upper_limit = 1000
